### ISSUE TITLE
Developments - scoping out projects and popout information to include

### ISSUE THREAD

**Issue by kaylapatel** [codeforboston/mattapan-mapping#10]
Discuss with Mattapan Mapping Project about scope and type of developments to include, how to integrate other research and community perspectives beyond what is on bpda sites

**Comment by barryfradkin** [comment]
@kaylapatel what is the next step on this, is there still more to discuss regarding other community perspectives?

**Comment by kaylapatel** [comment]
I think for the initial prototype this is it. Next, I was going to see which of the CDP team's alternattive images could complement these popups. It would also be great to see if users could comment on the different popups if possible.

**Comment by jedpittman** [comment]
Based on Kayla's comment, I think this is done. I am closing.
