### ISSUE TITLE
Audio clips (oral histories)

### ISSUE THREAD

**Issue by thadk** [codeforboston/mattapan-mapping#13]
Slack thread: https://cfb-public.slack.com/archives/C01T7228REJ/p1621385449014700

From May 18th meeting
- Idea: Record Ambient Sound from Mattapan area if desired (though interaction is required to play sound of course)
- This effort is distinct from their historical [StoryMap](https://www.esri.com/en-us/arcgis/products/arcgis-storymaps/overview) which is led by the Tufts professor.
- For now, main data to present is from the oral history interviews with residents which are currently residing in the Google Drive (see the Slack thread for the link).
- Most of the oral history files have a latitude and longitude – these will be in a spreadsheet collected quickly using https://voter.smithwebtek.com OR https://observablehq.com/@thadk/massachusetts-boston-geosearch-api .
- Geotagged imagery also in this effort.
- Example Google Sheet to Javascript via AWS API Gateway: https://qzk6eqs975.execute-api.us-east-1.amazonaws.com/beta https://github.com/thadk/youthmappers-chapter-map
- Alternative approach: `https://cors-anywhere.herokuapp.com/https://labs.zero.sh/api/gs2json?format=2&url=https://docs.google.com/spreadsheets/d/1dwN2xwFd9CyRnbF_KQmiYCIcdTzcZjo6WU0ip2QU5gQ/edit#gid=0` using https://zero.sh/labs/gs2json via https://observablehq.com/@triptych/google-sheets-to-json

Tues June 1: Have spreadsheet on the leaflet map via Pull Request. Work on SoundCloud embed. Talk about images.
Tues June 7: Finalize soundcloud embed format and popups from spreadsheet.
Tues June 14: Finalize the spreadsheet
Friday June 18th: Demo to Sasaki

**Comment by jedpittman** [comment]
These are done for demo.
