### ISSUE TITLE
Need a CSV file of locations

### ISSUE THREAD

**Issue by jkoren** [codeforboston/mattapan-mapping#18]

**Comment by barryfradkin** [comment]
@jkoren could you please clarify which locations you're looking for? Would this be for the recent housing developments? Thanks!

**Comment by jkoren** [comment]
This is complete.  There is not much information found about[ Brookview House II.](http://www.bostonplans.org/projects/development-projects/brookview-house-ii)   
The list is a csv file stored [here:](https://github.com/codeforboston/mattapan-mapping/blob/main/assets/csvFiles/Mattapan_BPDA_Developments.csv)
