### ISSUE TITLE
Add Morton St Corridor Boundary

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/mattapan-mapping#21]
Add Morton St Corridor Boundary. 
On the menu, should be right above River Street.

When adding morton street, make sure that we name it "Corridor"
@tejasvis also, for the first four (Blue Hill, Cummins, Morton, River), we should drop the word "Boundary" and replace with "Corridor"

**Comment by tejasvis** [comment]
Merged and closed in  #23

**Comment by jedpittman** [comment]
@tejasvis congrats on your first pr!
