### ISSUE TITLE
Setup loading of csv as blurbs for elements in map

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/mattapan-mapping#27]
Setup loading of csv as blurbs for elements in map

**Comment by beekmarks** [comment]
I completed the work required to incorporate and display the Development data in the current demo within feature/development_projects_v1.0.0.

As part of these updates, I also merged the commits in this branch provided by @Shay McDonough as well as those from the feature/audio_map_overlay_1.0.0 branch provided by @BradSmith.

A PR was created and the contents of feature/development_projects_v1.0.0 were merged in to the Main branch.
