### ISSUE TITLE
Use "Fontsource" packages in lieu of Google Fonts

### ISSUE THREAD

**Issue by stvnwn** [codeforboston/mattapan-mapping#67]
Install
- `@fontsource/montserrat`
- `@fontsource/bad-script`
- `@fontsource/dm-sans`

and import them in a `Global` component from `emotion`, instead of using Google Fonts. 

Advantages of self-hosting fonts are listed [here](https://fontsource.org/docs/introduction#advantages).

**Comment by laudickson** [comment]
Ah this is nifty!

The 'original' fonts were grabbed randomly, for quick prototype purposes. After several meetings with Powerful Pathways, they landed on using Baron for title/header font and Lato for body font, so the list would look something like
* `@fontsource/baron`
* `@fontsource/lato`

Baron isn't part of Google Fonts but is a free OpenType font that internet has multiple resources, I'm not sure if fontsource has it. Lato for sure is a Google Font and likely is in fontsource as well.

Deprecating montserrat, bad-script, and dm-sans could be part of this work too

**Comment by stvnwn** [comment]
In my personal projects, I created my own `@fontsource` packages for fonts that aren't published on npm. So "Baron Neue" being missing from Google Fonts shouldn't be an issue. And yeah, if "Montserrat", "Bad Script", and "DM Sans" aren't being used, then they should be removed.

However, I am concerned that I haven't found a license for "Baron Neue" yet if it isn't part of Google Fonts; I'd like to learn where Powerful Pathways found the font.
