### ISSUE TITLE
Design - Overall Look/Color-Coding Elements

### ISSUE THREAD

**Issue by morrisond7** [codeforboston/mattapan-mapping#8]
- Reviewed features + functionality that will be in the June 18 demo
- Allentza will start exploring color-coding for interactive elements:

> Audio clips (oral histories)
> Development projects
> Community landmarks
> Boundaries (tbd on boundary types)

Early ideation: [https://jamboard.google.com/d/1vyuLpGDBk8IVLyb43xdCB6Cm-4umQ39TNNJM2SUeIaM/viewer?f=0](url)

**Comment by morrisond7** [comment]
- First proposed color palette (passes color blind filters, though should ideally be checked with an individual living with color blindness)
- Next steps:
> Add a few more color palettes, get feedback from CfB team on preferred palette
> Mockup elements w/correct colors
> Properly implement final palette into CSS
> Identify granularity level of boundaries w/a stakeholder - can color-coding be condensed to 2-3 broad types?

Attached are screenshots + hex files of the new color palette (first image); old colors from existing CSS are included as an alternative palette (second image)


![palette-proposed](https://user-images.githubusercontent.com/29556967/120018810-a4cfce00-bfb5-11eb-8b9e-be5ff676ed02.png)



![palette-current](https://user-images.githubusercontent.com/29556967/120019169-1c056200-bfb6-11eb-9ac2-cfeb6cbcdb39.png)

**Comment by morrisond7** [comment]
- Received final color palette from Cecely
- Implemented onto mockup to ensure visibility
- Discussed future explorations for post-demo design work (thanks @mcdonoughsh   + @tejasvis!)

**Next steps:**

- Add colors/classes to the JS
- Confirm boundary types + colors
> Boundaries may get messy when many are selected on the demo - determine solutions if this is a problem later

**Comment by jedpittman** [comment]
These colors were added but not sure if we can close this yet?

**Comment by morrisond7** [comment]
@jedpittman I have some boundary colors I need to adjust in the JS; we can very quickly take care of this on Tuesday. Once that's done, we can close this issue.

**Comment by morrisond7** [comment]
I didn't realize the colors were already implemented! Closing this issue and creating a new one for post-demo work
